name: Daily Auto Commit

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a dummy commit
        run: |
          echo "Commit on $(date)" >> commit-log.txt
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add commit-log.txt
          git commit -m "🤖 Auto commit on $(date)"
          git push
